// PURITY: pure — no fs/network/clock (L3). Gate 2 (linker) check 11 — generated freshness: a
// byte-for-byte port of argument.py's render_index/render_dag/check_generated
// (argument.py:569-642), since the committed `argument/INDEX.md`/`DAG.md` in every golden-pass
// corpus fixture (linker-17..-20) were produced by the REAL AISM script and this check requires
// an EXACT byte match against a fresh render — any formatting drift here false-positives a
// spurious STALE on every clean fixture, not just the intentionally-stale one (linker-16).
//
// PRESENCE-CONDITIONAL (M1, bead rk-1rv; docs/memos/2026-07-18-aism-residue-audit.md R14).
// argument/INDEX.md and argument/DAG.md are AISM's transitional markdown mirror of the DAG,
// superseded by the M2.4 HTML render + M2.6 regenerate-and-diff gate. A general research tool
// must not force every repo to hand-create these mirrors just to pass `rk check`: each of the
// two files is checked ONLY when it is already present in the repo. Absence is never a finding —
// it means the mirror convention has not been adopted here, and that non-adoption is surfaced
// via `mirrorStatus` (consumed by linker.ts's coverage line), never silently. A PRESENT file that
// is stale still ERRORs exactly as before (byte-for-byte, unchanged). `aism_behavior: differs` —
// AISM's own `check_generated` (argument.py:632-642, `path.exists() else ""`) always treats an
// absent file as maximally stale and ERRORs; that behavior is the AISM residue this bead removes,
// not a stricter baseline to preserve, so it is not triaged into the usual rk-stricter-intended /
// rk-bug / ambiguous triad — a deliberate contract amendment, same footing as F5's reversal.
// Fixture: linker-25 (mirrors absent, golden pass). linker-16 (mirrors present, one stale) proves
// the presence-guard inversion would go red — see corpus/README.md.

import type { Finding } from "./framework";
import type { RepoSnapshot } from "./snapshot";
import type { Lemma } from "./linker-parse";

const GEN_HEADER = "<!-- GENERATED by scripts/argument.py --generate. Do not hand-edit. -->\n";
const DAG_ROUTE_NOTE =
  "<!-- OR-routes: `<id>__routeN` rhombus = one alternative route; solid edges into " +
  "it are that route's conjunctive members; the dashed `OR` edge into `<id>` means " +
  "any single route suffices. Unconditional deps draw plain solid edges. -->\n";
const LEGEND =
  "**Proof-status legend:** 🟩 validated · 🟦 proved · 🟨 seeded · " +
  "⬜ stated · 🟪 cited · 🟧 proved-mod-audit/conjecture/heuristic/numerical (NON-rigorous) · 🟥 open";

// proof-status colour classes (most-solid first); each node gets exactly one class — order is
// load-bearing for classline emission order in render_dag (argument.py:544-553).
const CLASSDEFS: Array<[string, string]> = [
  ["validated", "fill:#b7f7c2,stroke:#1a7f37,color:#0b3d18"],
  ["proved", "fill:#cfe3ff,stroke:#0969da,color:#0a3069"],
  ["seeded", "fill:#fff3c4,stroke:#bf8700,color:#5a4500"],
  ["stated", "fill:#eaecef,stroke:#8b949e,color:#24292f"],
  ["cited", "fill:#e7d6ff,stroke:#8250df,color:#3b1a73"],
  ["nonrigorous", "fill:#ffe8cc,stroke:#d97706,color:#7a3d00,stroke-dasharray:4 2"],
  ["open", "fill:#ffd6d6,stroke:#cf222e,color:#6e1119,stroke-dasharray:5 3"],
];
const ROUTE_CLASSDEF: [string, string] = ["routejct", "fill:#fbe7ff,stroke:#8250df,color:#3b1a73,stroke-dasharray:2 2"];

const NONRIGOROUS = new Set(["proved-mod-audit", "conjecture", "heuristic", "numerical"]);

/** The single proof-status colour class for a result (most-solid wins) — argument.py:569-581. */
function proofClass(l: Lemma): string {
  if (l.af === "validated") return "validated";
  if (l.status === "cited") return "cited";
  if (l.status === "proved") return "proved";
  if (l.status !== undefined && NONRIGOROUS.has(l.status)) return "nonrigorous";
  if (l.kind === "open-problem" || l.status === "open") return "open";
  if (l.af === "seeded") return "seeded";
  return "stated";
}

function byIdAsc(lemmas: Lemma[]): Lemma[] {
  return [...lemmas].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** argument.py:584-591, `render_index`. */
export function renderIndex(lemmas: Lemma[]): string {
  const rows = ["| id | kind | status | af | owner | contract |", "|---|---|---|---|---|---|"];
  for (const l of byIdAsc(lemmas)) {
    let c = l.contract ?? "";
    if (c.length > 80) c = `${c.slice(0, 80)}…`;
    rows.push(`| \`${l.id}\` | ${l.kind ?? "?"} | ${l.status ?? "?"} | ${l.af} | ${l.owner ?? "-"} | ${c} |`);
  }
  return `${GEN_HEADER}# Argument index (${lemmas.length} results)\n\n${rows.join("\n")}\n`;
}

/** argument.py:594-624, `render_dag`. */
export function renderDag(lemmas: Lemma[]): string {
  const ll = byIdAsc(lemmas);
  const nodes = ll.map((l) => `  ${l.id}["${l.id}<br/>${l.status ?? ""}/${l.af}"]`);

  const edges: string[] = [];
  for (const l of ll) for (const d of l.deps) edges.push(`  ${d} --> ${l.id}`);

  const routeNodes: string[] = [];
  const routeEdges: string[] = [];
  const routeJunctions: string[] = [];
  for (const l of ll) {
    l.routes.forEach((r, idx) => {
      const i = idx + 1;
      const jn = `${l.id}__route${i}`;
      routeJunctions.push(jn);
      routeNodes.push(`  ${jn}{"route ${i}"}`);
      for (const m of [...r].sort()) routeEdges.push(`  ${m} --> ${jn}`);
      routeEdges.push(`  ${jn} -. OR .-> ${l.id}`);
    });
  }
  const allEdges = [...edges].sort().concat([...routeEdges].sort());
  const totalEdges = allEdges.length;

  const classdefs = CLASSDEFS.map(([name, style]) => `  classDef ${name} ${style};`);
  classdefs.push(`  classDef ${ROUTE_CLASSDEF[0]} ${ROUTE_CLASSDEF[1]};`);

  const byClass = new Map<string, string[]>();
  for (const l of ll) {
    const cls = proofClass(l);
    const arr = byClass.get(cls) ?? [];
    arr.push(l.id);
    byClass.set(cls, arr);
  }
  const classlines: string[] = [];
  for (const [name] of CLASSDEFS) {
    const ids = byClass.get(name);
    if (ids && ids.length > 0) classlines.push(`  class ${[...ids].sort().join(",")} ${name};`);
  }
  if (routeJunctions.length > 0) {
    classlines.push(`  class ${[...routeJunctions].sort().join(",")} ${ROUTE_CLASSDEF[0]};`);
  }

  const body = [...classdefs, ...nodes, ...routeNodes, ...allEdges, ...classlines].join("\n");
  const header = `${GEN_HEADER}${DAG_ROUTE_NOTE}# Argument DAG (${ll.length} results, ${totalEdges} edges)\n\n`;
  return `${header}${LEGEND}\n\n\`\`\`mermaid\ngraph LR\n${body}\n\`\`\`\n`;
}

const GENERATED_FILES: Array<[string, (lemmas: Lemma[]) => string]> = [
  ["argument/INDEX.md", renderIndex],
  ["argument/DAG.md", renderDag],
];

/** One mirror file's adoption status, for the linker gate's coverage line (R14: absence must be
 * visible, never a silent skip — CLAUDE.md L2). `label` is the bare filename stem ("INDEX",
 * "DAG"). */
export interface MirrorStatus {
  path: string;
  label: string;
  present: boolean;
}

export interface GeneratedCheckResult {
  findings: Finding[];
  mirrorStatus: MirrorStatus[];
}

/** Check 11 — generated freshness (argument.py:632-642,698-701), PRESENCE-CONDITIONAL per file
 * (R14, bead rk-1rv — see this file's header comment). A mirror file absent from the snapshot is
 * read as "convention not adopted": no finding, `mirrorStatus` records it for the coverage line.
 * A PRESENT mirror file must still byte-equal a fresh render of the current shard set — unchanged
 * from the pre-R14 contract. */
export function checkGenerated(snapshot: RepoSnapshot, lemmas: Lemma[]): GeneratedCheckResult {
  const findings: Finding[] = [];
  const mirrorStatus: MirrorStatus[] = [];
  for (const [path, render] of GENERATED_FILES) {
    const present = snapshot.has(path);
    const label = path.slice(path.lastIndexOf("/") + 1).replace(/\.md$/, "");
    mirrorStatus.push({ path, label, present });
    if (!present) continue; // R14: absent mirror = not adopted, never a finding.
    const have = snapshot.get(path)!;
    if (have !== render(lemmas)) {
      findings.push({
        severity: "ERROR",
        path,
        message: `${path} is STALE (deps/proof-status graph out of sync with the shards) — regenerate from the current shard set`,
      });
    }
  }
  return { findings, mirrorStatus };
}
