#!/usr/bin/env python3
"""rkl_status.py -- pure status semantics. No filesystem access.

Own status (what the row asserts), by kind:
  def                      quoted | stipulated         (quoted needs a PROVENANCE row)
  assumption               assumed
  cited                    cited                        (terminal; needs a PROVENANCE row)
  lemma prop thm cor conj obs
                           proved | sketched | numerical | conjectured | open | refuted
Derived (printed) status adds:
  <base>-conditional       rests, transitively, on an `assumed` row (banner names the ids);
                           base in {proved, sketched, numerical}
  unsupported              a dependency is refuted/open/conjectured/unsupported: the proof
                           route is broken; the claim is unproved, NOT refuted
Propagation: deps are AND-groups of OR-alternatives ("a; b | c"). A group's strength is its
best alternative; the claim is capped by its weakest group. `numerical` is a ceiling.
"""
from rkl_parse import split_deps

DEF_STATUS = {"quoted", "stipulated"}
RESULT_STATUS = {"proved", "sketched", "numerical", "conjectured", "open", "refuted"}
KIND_STATUS = {"def": DEF_STATUS, "assumption": {"assumed"}, "cited": {"cited"}}
RESULT_KINDS = {"lemma", "prop", "thm", "cor", "conj", "obs"}
KINDS = RESULT_KINDS | set(KIND_STATUS)
REVIEWED = {"proved", "refuted"}  # both need a receipt-bound independent verdict
LABEL_PREFIX = {"def": "def", "lemma": "lem", "prop": "prop", "thm": "thm", "cor": "cor",
                "conj": "conj", "obs": "obs", "assumption": "asm", "cited": "cit"}

# Total order used only to pick the best OR-alternative and the weakest AND-group.
STRENGTH = ["refuted", "unsupported", "open", "conjectured", "numerical-conditional", "numerical",
            "sketched-conditional", "sketched", "proved-conditional", "assumed", "proved", "cited"]
RANK = {s: i for i, s in enumerate(STRENGTH)}
PRINTABLE = set(STRENGTH)


def allowed_status(kind):
    return KIND_STATUS.get(kind, RESULT_STATUS)


def compute(claims):
    """claims: {id: row}. Returns (effective {id: status}, conditional_on {id: sorted ids}, cycles)."""
    eff, cond, cycles, stack = {}, {}, set(), []

    def visit(cid):
        if cid in eff:
            return eff[cid]
        if cid in stack:
            cycles.add(cid)
            return "unsupported"
        stack.append(cid)
        row = claims[cid]
        own, kind = row["status"], row["kind"]
        assumptions = set()
        if kind == "def":
            result = own
        elif kind == "assumption":
            result, assumptions = "assumed", {cid}
        elif kind == "cited" or own in ("refuted", "open", "conjectured"):
            result = own
        else:  # proved | sketched | numerical, with deps
            weakest = None
            for group in split_deps(row["deps"]):
                best = best_id = None
                for alt in group:
                    if alt not in claims or claims[alt]["kind"] == "def":
                        continue  # unknown deps are reported by the checks; defs do not propagate
                    s = visit(alt)
                    if best is None or RANK[s] > RANK[best]:
                        best, best_id = s, alt
                if best is None:
                    continue
                assumptions |= cond.get(best_id, set())
                if weakest is None or RANK[best] < RANK[weakest]:
                    weakest = best
            if weakest is not None and RANK[weakest] <= RANK["conjectured"]:
                result = "unsupported"
            else:
                base = own
                if own != "numerical" and weakest in ("numerical", "numerical-conditional"):
                    base = "numerical"
                elif base == "proved" and weakest in ("sketched", "sketched-conditional"):
                    base = "sketched"
                result = base + ("-conditional" if assumptions else "")
        stack.pop()
        eff[cid] = result
        cond[cid] = assumptions
        return result

    for cid in claims:
        visit(cid)
    return eff, {k: sorted(v) for k, v in cond.items()}, cycles


def banner_tex(claims, eff, cond, config):
    """Deterministic report/generated/status.tex."""
    main = config.get("main")
    esc = lambda s: s.replace("_", "\\_")
    lines = ["% GENERATED by scripts/check.py --regen from CLAIMS.md. Do not edit; `make check` diffs it.",
             "\\begin{center}\\small\\begin{tabular}{llll}\\hline",
             "id & kind & status & conditional on \\\\ \\hline"]
    for cid in sorted(claims):
        r = claims[cid]
        if r["kind"] == "def":
            continue
        mark = " (main)" if cid == main else ""
        on = ", ".join("\\texttt{%s}" % esc(a) for a in cond.get(cid, []) if a != cid) or "--"
        lines.append("\\texttt{%s}%s & %s & \\textbf{%s} & %s \\\\" % (esc(cid), mark, r["kind"], eff[cid], on))
    lines.append("\\hline\\end{tabular}\\end{center}")
    if main and main in eff:
        lines.append("\\noindent\\textbf{Headline:} \\texttt{%s} is \\textbf{%s}%s." % (
            esc(main), eff[main],
            (" conditional on " + ", ".join("\\texttt{%s}" % esc(a) for a in cond.get(main, []))) if cond.get(main) else ""))
    if config.get("stakes", "report") == "note":
        lines.append("\\noindent\\emph{Stakes: note --- nothing here has been independently reviewed.}")
    sf = sorted(c for c, r in claims.items() if r["status"] in REVIEWED and "single-family" in r["review"])
    if sf:
        lines.append("\\noindent\\emph{Single-family review only:} " + ", ".join("\\texttt{%s}" % esc(a) for a in sf) + ".")
    return "\n".join(lines) + "\n"
