// EDGE — fs + subprocess (af/fr/bd, via src/store/build-graph.ts and src/cli/render.ts's
// `renderSiteFromRepo`). Gate 7's `render-site-v1` entries are RECOGNIZED but never regenerated by
// the pure gate (src/gates/freshness.ts stays L3-pure); this module is the edge that produces the
// "expected bytes" the gate diffs, plus the snapshot augmentation that makes the "have" side
// visible. Split out of src/cli/check.ts (which was 390 lines, past CLAUDE.md Rule 4's 280 cap)
// when rk-xbsx added the reproducibility probe — one module, one job.
//
// rk-xbsx (2026-07-25): WHAT A "STALE" IS ALLOWED TO MEAN.
// B2 routed this regeneration through `renderSiteFromRepo`, the same option-assembly seam `rk
// render` uses — which reads af, fr (twice: `buildGraphDocument`'s join read and
// `loadFrResiduals`'s display read) and bd through LIVE subprocesses. The gate then byte-diffs
// that against the artifact on disk. So the "expected" side is not a function of the repo alone,
// and a difference has three possible causes, which this module refuses to conflate:
//
//   1. DRIFT — the repo's own ground truth (registry shards, and af/fr/bd state, which per PRD D1's
//      "per-repo ground truth" lives IN the repo: .af/, .frontier/, .beads/) moved on since the
//      render. The artifact really is out of date. Convergent and actionable: `rk render` clears
//      it. This is the ONLY cause allowed to produce Gate 7's STALE verdict.
//   2. NON-REPRODUCIBILITY — the generator does not produce the same bytes twice on an unchanged
//      repo (a non-deterministic export, or external state churning mid-check). There is no
//      well-defined "expected" side at all, so no verdict can be drawn from it. DETECTED, not
//      assumed away: this module regenerates TWICE and byte-compares (see `prepareRenderSiteExternalRegen`).
//   3. DEGRADED FIDELITY — a reader could only reach its reduced-fidelity fallback (`af:
//      ledger-fallback`, `fr: log-fallback`), so the expected bytes describe the VERIFIER's
//      environment as much as the repo. Re-rendering would not fix the artifact; it would re-pin
//      it to the degraded output, and the STALE would return the moment the source came back.
//      Reported as `degraded`, which the gate turns into its own non-STALE ERROR.
//
// Causes 2 and 3 are the "cry wolf" class B2 just fixed by a different door: a freshness signal
// the user cannot clear trains them to ignore the one mechanism PRD SC2's "no drift by
// construction" rests on. Both now FAIL CLOSED (still an ERROR, never a silent pass) while being
// named as what they are, never as drift. Note the asymmetry that makes this sound: degradation
// only matters at VERIFICATION time. A render made under a degraded reader and verified under an
// authoritative one yields a real, convergent STALE — correctly reported as drift.
//
// COST: two full regenerations (2x af/fr/bd exports, 2x render) per `rk check`, and only when the
// manifest actually declares a `render-site-v1` path (`paths.length === 0` short-circuits before
// touching af/fr/fs at all). CLAUDE.md L6: cost never outranks the validity barrier, and the
// alternative — assuming `fr export` is deterministic — is exactly the assumption rk-xbsx was
// filed against.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildGraphDocument } from "../store/build-graph";
import { renderSiteFromRepo } from "./render";
import type { SourceStatuses } from "../render/diagnostics-view";
import type { ExternalRegenResult } from "../gates/freshness";
import type { GateConfig } from "../gates/config";
import type { RepoSnapshot } from "../gates/snapshot";

/** Injectable af/fr command overrides — same seam `src/cli/render.ts`'s `RenderCommandDeps` uses,
 * so a test can force the af/fr-absent or af/fr-degraded path deterministically without touching
 * `$PATH`. */
export interface CheckCommandDeps {
  afCommand?: readonly string[];
  frCommand?: readonly string[];
}

/** One complete regeneration: the `index.html` bytes it produced, and the fidelity of every
 * live-external reader that fed it. Both halves are needed to decide what a later byte difference
 * is allowed to MEAN — see this file's header. */
export interface RegenAttempt {
  bytes: string;
  sources: SourceStatuses;
}

/** Human-readable text for the reduced-fidelity states only. Deliberately NOT `absent`: a source
 * that was never engaged (no `.frontier/`, no af-tracked node, no `.beads/`) is a legitimate,
 * presence-conditional non-adoption — the stance src/render/diagnostics-view.ts already takes, and
 * the stance that keeps a campaign which simply does not use fr from getting an unclearable
 * finding on every check. Only "engaged but only a weaker reader could reach it" makes the
 * expected bytes environment-dependent. Wording mirrors diagnostics-view.ts's own labels. */
function fidelityLosses(sources: SourceStatuses): string[] {
  const out: string[] = [];
  if (sources.af === "ledger-fallback") out.push("af: ledger fallback (reduced fidelity)");
  if (sources.fr === "log-fallback") out.push("fr: log fallback (reduced fidelity)");
  return out;
}

/** 1-indexed first differing line — mirrors src/gates/freshness.ts's own `firstDiffLine` so the
 * two halves of a Gate 7 message locate a divergence the same way. Duplicated rather than
 * imported: freshness.ts keeps it private, and an edge module reaching into a pure gate's
 * internals to share four lines is the wrong direction of dependency. */
function firstDiffLine(a: string, b: string): number {
  const al = a.split("\n");
  const bl = b.split("\n");
  const n = Math.min(al.length, bl.length);
  for (let i = 0; i < n; i++) if (al[i] !== bl[i]) return i + 1;
  return n + 1;
}

/** PURE (no fs/subprocess): turns two independent regeneration attempts into the single
 * `ExternalRegenResult` Gate 7 consumes. Exported so the taxonomy itself is directly testable
 * without needing to make a real `fr export` misbehave on demand.
 *   - attempts disagree  ⇒ `ok:false` — cause 2, no verdict is drawable at all.
 *   - a reader degraded  ⇒ `ok:true` + `degraded` — cause 3, the gate withholds the drift verdict
 *                          but still ERRORs on a difference.
 *   - otherwise          ⇒ `ok:true` — a difference now means drift, and only drift. */
export function classifyRegen(a: RegenAttempt, b: RegenAttempt): ExternalRegenResult {
  if (a.bytes !== b.bytes) {
    const line = firstDiffLine(a.bytes, b.bytes);
    return {
      ok: false,
      reason:
        `the regeneration is NOT reproducible within a single 'rk check' run — two back-to-back ` +
        `regenerations of an unchanged repo differed (first at line ${line}). The generator reads af/fr/bd ` +
        `through live subprocesses, so the "expected" side of a freshness diff is not well-defined here ` +
        `and NO drift verdict can be drawn from it (this is deliberately not reported as STALE). ` +
        `next: check whether 'fr export'/'af export' output varies between two invocations on an ` +
        `unchanged repo, or whether another process is writing .frontier/.af/.beads during 'rk check'`,
    };
  }
  const losses = [...new Set([...fidelityLosses(a.sources), ...fidelityLosses(b.sources)])].sort();
  if (losses.length > 0) return { ok: true, bytes: a.bytes, degraded: losses.join("; ") };
  return { ok: true, bytes: a.bytes };
}

type AttemptResult = { ok: true; attempt: RegenAttempt } | { ok: false; reason: string };

/** ONE regeneration, through the exact path `rk render` uses (B2's single option-assembly seam).
 * A structurally incomplete build is refused here, not diffed: "a build this incomplete must never
 * be the expected side of a freshness diff" (M2 boundary review blocker #2). */
function regenerateOnce(root: string, config: GateConfig, deps: CheckCommandDeps): AttemptResult {
  const buildResult = buildGraphDocument(root, { afCommand: deps.afCommand, frCommand: deps.frCommand });
  const { diagnostics } = buildResult;
  if (!diagnostics.isStructurallyComplete) {
    const lossCount =
      diagnostics.structuralLoss.registrySkips.length + diagnostics.structuralLoss.frMalformedLines.length;
    const skipDetail = diagnostics.structuralLoss.registrySkips.map((s) => `${s.path} (${s.reason})`).join("; ");
    const frDetail = diagnostics.structuralLoss.frMalformedLines
      .map((l) => `fr log line ${l.lineNo} (${l.snippet})`)
      .join("; ");
    const detail = [skipDetail, frDetail].filter((s) => s.length > 0).join("; ");
    return {
      ok: false,
      reason:
        `the GraphDocument build is structurally incomplete (${lossCount} structural-loss ` +
        `entr${lossCount === 1 ? "y" : "ies"}: ${detail || "see rk render/rk graph for detail"}) -- a build ` +
        `this incomplete must never be used as the "expected" side of a freshness diff`,
    };
  }
  // B2: `rk render` and `rk check` regenerate through the SAME function, so a seventh render
  // option is seen by Gate 7 automatically. The one residual (`--title`/`--north-star`, CLI-only
  // overrides this path has no equivalent of) is detected and warned AT RENDER TIME by
  // src/cli/render.ts's `checkDivergenceWarning`, never left to surface here as a mystery STALE.
  const { site } = renderSiteFromRepo(root, buildResult.doc, diagnostics.sources, {
    northStarId: config.northStarId,
    frCommand: deps.frCommand,
  });
  const indexFile = site.files.find((f) => f.path === "index.html");
  if (!indexFile) {
    return {
      ok: false,
      reason:
        `renderSite's pure API did not produce an "index.html" file (produced: ` +
        `${site.files.map((f) => f.path).join(", ") || "none"})`,
    };
  }
  return { ok: true, attempt: { bytes: indexFile.contents, sources: diagnostics.sources } };
}

/** M2 boundary review blocker #3 + rk-xbsx. Produces Gate 7's edge-supplied expected bytes, or a
 * structured failure reason, for every declared `render-site-v1` path. Never throws: every failure
 * mode becomes an `ok:false` the gate turns into a loud per-path ERROR. Regenerates TWICE — see
 * this file's header for why a single regeneration cannot tell drift from churn. */
export function prepareRenderSiteExternalRegen(
  root: string,
  paths: readonly string[],
  config: GateConfig,
  deps: CheckCommandDeps,
): ReadonlyMap<string, ExternalRegenResult> {
  const map = new Map<string, ExternalRegenResult>();
  if (paths.length === 0) return map;

  const fill = (result: ExternalRegenResult): ReadonlyMap<string, ExternalRegenResult> => {
    for (const p of paths) map.set(p, result);
    return map;
  };

  try {
    const first = regenerateOnce(root, config, deps);
    if (!first.ok) return fill({ ok: false, reason: first.reason });
    const second = regenerateOnce(root, config, deps);
    if (!second.ok) {
      return fill({
        ok: false,
        reason:
          `the regeneration is NOT reproducible within a single 'rk check' run — the first attempt ` +
          `succeeded and an immediate second attempt on the same unchanged repo failed (${second.reason}). ` +
          `No drift verdict can be drawn from an unstable generator, so nothing is reported as STALE`,
      });
    }
    return fill(classifyRegen(first.attempt, second.attempt));
  } catch (e) {
    const message = e instanceof Error ? `${e.name}: ${e.message}` : String(e);
    return fill({ ok: false, reason: `building the GraphDocument / rendering the site threw: ${message}` });
  }
}

/** `src/store/snapshot-load.ts`'s `RepoSnapshot` text map is deliberately bounded to the six
 * gates' declared Inputs (definitions/, argument/, proofs/, refs/, runs/, report/, .rk/ —
 * "explicit include globs from the contract, no kitchen-sink") — it does NOT include `rk
 * render`'s own output directory (`build/site/` by default), which is not any pre-M2.6 gate's
 * Input. Gate 7 still needs the ACTUAL on-disk bytes of a declared `render-site-v1` path to diff
 * against (the "have" side). Rather than widen the loader's include rules (join-lane territory),
 * this reads the handful of declared render-site-v1 paths directly, at the edge, and hands
 * freshness's own gate invocation an augmented snapshot carrying just those extra entries — every
 * OTHER gate keeps seeing the original, untouched snapshot. A path genuinely absent from disk is
 * left unaugmented; Gate 7's own declared-but-missing check reports that, unchanged. */
export function augmentSnapshotForRenderSite(
  snapshot: RepoSnapshot,
  root: string,
  paths: readonly string[],
): RepoSnapshot {
  let extra: Map<string, string> | undefined;
  for (const p of paths) {
    if (snapshot.has(p)) continue; // already visible under an existing include rule
    let text: string;
    try {
      text = readFileSync(join(root, ...p.split("/")), "utf8");
    } catch {
      continue; // genuinely absent from disk -- Gate 7's own declared-but-missing ERROR handles this
    }
    if (!extra) extra = new Map<string, string>();
    extra.set(p, text);
  }
  if (!extra) return snapshot;
  const merged = new Map<string, string>(snapshot);
  for (const [k, v] of extra) merged.set(k, v);
  return Object.assign(merged, {
    sha256: snapshot.sha256,
    tracked: snapshot.tracked,
    dirs: snapshot.dirs,
  }) as RepoSnapshot;
}
