// PURITY: pure — no fs/network/clock (L3). THE GENERATED CARD (bead rk-nsex;
// docs/design/NOTES-2026-08-20-qpcp-campaign-plan.md section 4, "Generated cards").
//
// "Cards are the most dangerous artifact in the pipeline: an agent answering from a card trusts
// it." So the card is not written by anyone. It is RENDERED, deterministically and with no clock
// input, from the AUTHORED extraction record (`refs/records/<source-id>/L1-<n>.json`) plus that
// record's review record; `.rk/generated.json` declares it with generator `cards-v1` and Gate 7
// byte-diffs it on every `rk check`. Hand-editing a card is therefore a freshness failure, not a
// silent improvement of the truth an agent will read.
//
// THE REFUSAL STUB. A record that is absent from Check 11's `usable` map renders a card with NO
// mathematical content at all — just its identity and the reason. This includes source/anchor/
// staleness defects as well as a review that is absent, bound to other bytes, or not VALID. The alternative
// (render the statement and mention the missing review in a footer) puts the exact text an agent
// will quote in front of it and relies on the agent reading the caveat. An empty card cannot be
// misread. Recomputing the record digest here rather than trusting the review's own `card_sha256`
// is what makes the stub honest: the renderer checks the binding itself.
//
// Deterministic by construction: no clock, no environment, no iteration over an unordered map —
// the record's own field order is fixed by its schema and its `hypotheses` array order is data.

import { canonicalRecordSha256 } from "../gates/canonical-json";
import { readLockFacts } from "../gates/refs-extraction";
import { collectRecords } from "../gates/refs-records";
import type { L1Record, ReviewRecord } from "../gates/refs-records";
import { verifyRecords } from "../gates/refs-records-verify";
import type { RepoSnapshot } from "../gates/snapshot";

export const CARDS_PREFIX = "refs/cards/";
export const CARD_GENERATOR = "cards-v1";
const CARD_PATH_RE = /^refs\/cards\/([^/]+)\/(L1-[1-9][0-9]*)\.md$/;
const RECORD_PATH_RE = /^refs\/records\/([^/]+)\/(L1-[1-9][0-9]*)\.json$/;

/** `refs/records/<src>/L1-<n>.json` -> `refs/cards/<src>/L1-<n>.md`. */
export function cardPathForRecord(recordPath: string): string | undefined {
  const m = RECORD_PATH_RE.exec(recordPath);
  return m ? `${CARDS_PREFIX}${m[1]!}/${m[2]!}.md` : undefined;
}

/** The inverse — the record a declared card path is rendered from. */
export function recordPathForCard(cardPath: string): string | undefined {
  const m = CARD_PATH_RE.exec(cardPath);
  return m ? `refs/records/${m[1]!}/${m[2]!}.json` : undefined;
}

const HEADER = (recordPath: string) =>
  [
    `<!-- GENERATED by 'rk render cards' (generator '${CARD_GENERATOR}') from ${recordPath} and its`,
    "     review record. AUTHORED source: the record. Do not hand-edit — Gate 7 byte-diffs this",
    "     file (docs/gate-contracts.md Gate 7); an edit here is a freshness failure, and the record",
    "     is the truth this is a view of. -->",
    "",
  ].join("\n");

function fence(text: string): string[] {
  return ["```text", ...text.split("\n"), "```"];
}

/** The card an admissible record renders to, or the refusal stub when its review does not bind
 * it. `review` is the review record found for `record`, or undefined when none exists. */
export function renderCard(record: L1Record, review: ReviewRecord | undefined, check11Usable: boolean): string {
  const digest = canonicalRecordSha256(record.value);
  const refusal = refusalReason(review, digest, check11Usable);
  const lines: string[] = [HEADER(record.path)];

  if (refusal !== undefined) {
    lines.push(
      `# ${record.resultLabel} — ${record.sourceId} (NOT ADMISSIBLE)`,
      "",
      `This card is deliberately empty: ${refusal}`,
      "",
      `- record: \`${record.path}\``,
      `- record_sha256: \`${digest}\``,
      "",
      "No statement, hypothesis or restatement from this record is rendered here, and none of it may",
      "be cited: an extraction becomes readable only through a review record bound to these exact",
      "bytes (schemas/card-review.v1.json, docs/gate-contracts.md Gate 3 Check 11).",
      "",
    );
    return lines.join("\n");
  }

  const r = review!;
  lines.push(
    `# ${record.resultLabel} — ${record.sourceId}`,
    "",
    `- record: \`${record.path}\``,
    `- record_sha256: \`${digest}\``,
    `- review: ${r.verdict} by ${r.reviewer.family}/${r.reviewer.backend}/${r.reviewer.model} (\`${r.path}\`)`,
    `- source: \`${record.source}\`, payload sha256 \`${record.payloadSha256}\``,
    ...(record.extractionSha256 !== undefined ? [`- extraction sha256: \`${record.extractionSha256}\``] : []),
    `- statement range: \`${record.statementRange}\``,
    `- profile: \`${record.profile}\``,
    `- proof locus: \`${record.proofLocus}\``,
    "",
    "## Statement, as printed in the source",
    "",
    ...fence(record.statementVerbatim),
    "",
    "## Statement, in register notation",
    "",
    record.statementBlessed,
    "",
    "## Hypotheses",
    "",
  );
  if (record.hypotheses.length === 0) lines.push("None recorded (the printed statement carries no hypothesis clause).", "");
  else {
    for (const h of record.hypotheses) lines.push(`- \`${h.anchor}\` — ${h.text}`);
    lines.push("");
  }
  lines.push("## Conclusion", "", record.conclusion, "", "## Review", "");
  for (const clause of r.clauses) lines.push(`- ${clause.name}: ${clause.value} — ${clause.note}`);
  lines.push("");
  if (r.findings.length === 0) lines.push("No findings recorded.", "");
  else {
    lines.push("Findings:", "");
    for (const f of r.findings) lines.push(`- ${f}`);
    lines.push("");
  }
  return lines.join("\n");
}

function refusalReason(review: ReviewRecord | undefined, digest: string, check11Usable: boolean): string | undefined {
  if (!review) return "this extraction record has no review record, so nothing has independently checked it against the source";
  if (review.cardSha256.toLowerCase() !== digest.toLowerCase()) {
    return `the review record (\`${review.path}\`) is bound to card_sha256 \`${review.cardSha256}\`, but the record's canonical bytes hash \`${digest}\` — the record was edited after it was reviewed`;
  }
  if (review.verdict !== "VALID") return `the review record (\`${review.path}\`) records verdict ${review.verdict}`;
  if (review.falseClauses.length > 0) {
    return `the review record (\`${review.path}\`) says VALID while answering false to: ${review.falseClauses.join(", ")}`;
  }
  if (!check11Usable) {
    return "this extraction record did not pass every Gate 3 Check 11 source, anchor, staleness, envelope and review clause";
  }
  return undefined;
}

export type CardRegen = { ok: true; bytes: string } | { ok: false; reason: string };

/** The `cards-v1` generator: what a fresh render of `cardPath` produces from this snapshot.
 * Fail-closed — a card path whose record is absent, unparseable or malformed yields `ok: false`
 * with a reason, never bytes and never a silent pass (Gate 7 turns it into a named ERROR). */
export function renderCardForPath(snapshot: RepoSnapshot, cardPath: string): CardRegen {
  const recordPath = recordPathForCard(cardPath);
  if (recordPath === undefined) {
    return { ok: false, reason: `${cardPath} is not a card path (expected ${CARDS_PREFIX}<source-id>/L1-<n>.md)` };
  }
  if (!snapshot.has(recordPath)) {
    return { ok: false, reason: `no extraction record at ${recordPath} — a card is a view of a record, so there is nothing to render` };
  }
  const records = collectRecords(snapshot);
  const record = records.l1.find((r) => r.path === recordPath);
  if (!record) {
    return { ok: false, reason: `${recordPath} exists but is not a shape-valid extraction record (see this run's Gate 3 [record-*] findings)` };
  }
  const verified = verifyRecords(snapshot, readLockFacts(snapshot), records);
  return { ok: true, bytes: renderCard(record, records.reviews.get(recordPath), verified.usable.has(recordPath)) };
}
