// ROLE: the GENERATED notation macro file, `definitions/notation/macros.tex` — one
// `\newcommand` per notation-register shard, so the campaign's LaTeX writes the blessed form and
// nothing else. Adopted through `.rk/generated.json` under generator `notation-macros` and
// byte-diffed by Gate 7 (src/gates/freshness.ts), which is what makes a hand-edited macro file a
// blocking ERROR rather than a quiet divergence between the register and the prose.
// Contract: docs/gate-contracts.md Gate 1 "Notation shards" + Gate 7. rk-5lzf / LB5.
// PURITY: pure — no fs/network/clock (L3). Called by Gate 7 itself, so it must be pure by
// construction: a generator that reads the clock or the filesystem can never be byte-diffed
// (rule 9 — "generated vs authored, never mixed").
//
// DETERMINISM IS THE CONTRACT. Sorted by shard `id`, no timestamps, no host paths, no counts that
// could drift — the same register must render the same bytes forever, or Gate 7 reports a STALE
// artifact on a repo nobody touched and trains its readers to ignore the one signal PRD SC2 rests
// on. The tests in test/render/macros-tex.test.ts assert exactly that.

import type { RepoSnapshot } from "../gates/snapshot";
import { parseNotationShards } from "../gates/notation-shards";

export const MACROS_PATH = "definitions/notation/macros.tex";
/** The `.rk/generated.json` generator id. Also a `GENERATORS` key in src/gates/freshness.ts. */
export const MACROS_GENERATOR = "notation-macros";

const HEADER = [
  `% ${MACROS_PATH} — GENERATED by rk (generator '${MACROS_GENERATOR}'). Do not hand-edit.`,
  "% Source of truth: the notation register, definitions/**/*.md shards with shard_type: notation.",
  "% Regenerate with 'rk render macros'; Gate 7 (freshness) byte-diffs this file on every check.",
  "% One \\newcommand per registered symbol, sorted by shard id.",
];

/** The macro body for a shard: its declared `expansion:`, or a visibly-marked stand-in.
 * A missing expansion is NOT an error here — Gate 1 owns what a notation shard must carry, and a
 * generator that refused to render would take the whole file down over one shard. It renders a
 * deterministic placeholder and says so on the line, so the gap is readable in the artifact
 * itself rather than only in a gate's output. */
function macroBody(symbol: string, expansion: string | undefined): { body: string; note: string } {
  if (expansion !== undefined && expansion.trim() !== "") return { body: expansion.trim(), note: "" };
  return { body: `\\ensuremath{\\mathsf{${symbol.slice(1)}}}`, note: "  % no expansion: declared in the shard" };
}

/** Renders the whole file. An empty register still renders a complete, stable file (header only):
 * the presence-conditional case is a legitimate day-1 state, and an adopted artifact that
 * disappears when the register empties would report as STALE rather than as empty. */
export function renderMacros(snapshot: RepoSnapshot): string {
  const shards = [...parseNotationShards(snapshot)].sort((a, b) =>
    (a.fields.id ?? a.path).localeCompare(b.fields.id ?? b.path),
  );
  const lines = [...HEADER, ""];
  for (const shard of shards) {
    if (shard.symbol === undefined) continue;
    const { body, note } = macroBody(shard.symbol, shard.fields.expansion);
    lines.push(`\\newcommand{${shard.symbol}}{${body}}${note}`);
  }
  return `${lines.join("\n")}\n`;
}
