// M1.1 template-set acceptance (bead rk-b8p). Makes the acceptance bar mechanical: the residue
// grep (c) is the exact form of "a domain expert finds no AISM-specific residue". The layout
// forbid-list encodes audit findings R1/R11/R13/R14 (docs/memos/2026-07-18-aism-residue-audit.md).
//
// L1 red-green: each assertion was watched fail first — plant a residue string in a .tmpl and (c)
// goes red; drop a required slot and (b) goes red; corrupt a header classification and (a) goes
// red; point a manifest entry at a missing template and (d) goes red. Restore, green.

import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync, existsSync } from "node:fs";
import { join } from "node:path";

const TEMPLATES_ROOT = join(import.meta.dir, "..", "..", "templates");

// Every .tmpl under templates/ (recursive), as paths relative to templates/.
function findTmpl(dir: string, base = ""): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    const rel = base ? `${base}/${entry}` : entry;
    if (statSync(abs).isDirectory()) out.push(...findTmpl(abs, rel));
    else if (entry.endsWith(".tmpl")) out.push(rel);
  }
  return out;
}

const TMPL_FILES = findTmpl(TEMPLATES_ROOT);
const read = (rel: string) => readFileSync(join(TEMPLATES_ROOT, rel), "utf8");

const VALID_CLASSIFICATIONS = ["authored-append-only", "rewritten-whole", "generated"];

// Constitution slots that must appear EXACTLY ONCE (uniqueness matters — a duplicated north-star
// or phase declaration is an authoring error). PROJECT_NAME is deliberately excluded: it recurs
// in the title and body by design.
const REQUIRED_UNIQUE_SLOTS = [
  "RK_SLOT_GOAL",
  "RK_SLOT_NORTH_STAR",
  "RK_SLOT_COMPUTE_BUDGET",
  "RK_SLOT_MODEL_POLICY",
  "RK_SLOT_PHASE",
  "RK_SLOT_AUDIT_CADENCE",
  "RK_SLOT_BRITTLENESS_SOFT_CAP",
];

// Case-insensitive residue tokens. A stamped repo carrying any of these fails rk-b8p by
// inspection (audit R12 landing-blocker made a grep).
const RESIDUE_TOKENS = ["aism", "almost-idempotent", "stochastic", "osborne", "tobias"];

// Layout residue the scaffold must never bake (audit R11/R13/R14).
const FORBIDDEN_PATHS = [
  "report/",
  "LEARNINGS.md",
  "SHARD_CATALOG.md",
  "argument/INDEX.md",
  "argument/DAG.md",
  "INDEX.md",
];

describe("templates / sanity", () => {
  test("the expected .tmpl set is present", () => {
    expect(TMPL_FILES.sort()).toEqual(
      [
        "CLAUDE.md.tmpl",
        "CONVENTIONS.md.tmpl",
        "FINDINGS.md.tmpl",
        "HANDOFF.md.tmpl",
        "PRD.md.tmpl",
        "docs/worklog.md.tmpl",
        "definitions/README.md.tmpl",
        "argument/README.md.tmpl",
      ].sort(),
    );
  });
});

describe("templates / (a) ROLE-UPDATE-POLICY-TRIGGER headers", () => {
  for (const rel of TMPL_FILES) {
    test(`${rel} carries a header with a valid classification`, () => {
      const body = read(rel);
      // The header is the leading HTML comment; it must carry all three fields in order.
      const header = body.slice(0, body.indexOf("-->"));
      expect(header).toContain("ROLE:");
      const upIdx = header.indexOf("UPDATE POLICY:");
      const trIdx = header.indexOf("TRIGGER:");
      expect(upIdx).toBeGreaterThanOrEqual(0);
      expect(trIdx).toBeGreaterThan(upIdx);
      // The classification is declared in the UPDATE POLICY segment, exactly one, never mixed
      // (PRD §3). Scope the match to that segment so unrelated prose (e.g. "generated by
      // rk render" in a router line) cannot count as a second classification.
      const updatePolicy = header.slice(upIdx, trIdx);
      const found = VALID_CLASSIFICATIONS.filter((c) => updatePolicy.includes(c));
      expect(found).toHaveLength(1);
    });
  }
});

describe("templates / (b) constitution required slots", () => {
  const body = read("CLAUDE.md.tmpl");
  const count = (slot: string) => body.split(`{{${slot}}}`).length - 1;

  for (const slot of REQUIRED_UNIQUE_SLOTS) {
    test(`{{${slot}}} appears exactly once`, () => {
      expect(count(slot)).toBe(1);
    });
  }

  test("shard-prefix and project-name slots are present (R12: per-repo, never a literal)", () => {
    expect(count("RK_SLOT_SHARD_PREFIX")).toBeGreaterThanOrEqual(1);
    expect(count("RK_SLOT_PROJECT_NAME")).toBeGreaterThanOrEqual(1);
  });

  test("the session-close audit trigger references the cadence slot and blocks close", () => {
    // Trigger must exist now and be exercisable (M1.1 acceptance): it names the cadence slot,
    // the exceed condition, and the block.
    const section = body.slice(body.indexOf("Session close"));
    expect(section).toContain("{{RK_SLOT_AUDIT_CADENCE}}");
    expect(section.toLowerCase()).toContain("cycles-since-last-audit");
    expect(section).toContain("BLOCKED");
  });
});

describe("templates / (c) residue grep — the acceptance bar", () => {
  for (const rel of TMPL_FILES) {
    test(`${rel} contains no AISM/TJO residue token`, () => {
      const lower = read(rel).toLowerCase();
      for (const token of RESIDUE_TOKENS) {
        expect(lower).not.toContain(token);
      }
    });
  }

  test("manifest.json contains no residue token", () => {
    const lower = readFileSync(join(TEMPLATES_ROOT, "manifest.json"), "utf8").toLowerCase();
    for (const token of RESIDUE_TOKENS) {
      expect(lower).not.toContain(token);
    }
  });
});

describe("templates / (d) manifest.json", () => {
  const manifest = JSON.parse(readFileSync(join(TEMPLATES_ROOT, "manifest.json"), "utf8"));

  test("parses and carries a semver template_version", () => {
    expect(manifest.template_version).toMatch(/^\d+\.\d+\.\d+$/);
  });

  test("every stamped entry's template file exists in templates/", () => {
    for (const entry of manifest.stamped) {
      if (entry.template === null) {
        expect(entry.classification).toBe("directory");
        continue;
      }
      expect(existsSync(join(TEMPLATES_ROOT, entry.template))).toBe(true);
      expect(VALID_CLASSIFICATIONS).toContain(entry.classification);
    }
  });

  test("every .tmpl on disk is referenced by at least one stamped entry", () => {
    const referenced = new Set(
      manifest.stamped.map((e: { template: string | null }) => e.template).filter(Boolean),
    );
    for (const rel of TMPL_FILES) expect(referenced.has(rel)).toBe(true);
  });

  test("the layout stamps exactly PRD:79-85 and bakes no forbidden residue path", () => {
    const paths: string[] = manifest.stamped.map((e: { path: string }) => e.path);
    for (const forbidden of FORBIDDEN_PATHS) {
      expect(paths.some((p) => p === forbidden || p.startsWith(forbidden))).toBe(false);
    }
    // The four content layers, refs, docs/worklog.md, and the four state dirs are all present.
    for (const required of [
      "definitions/",
      "argument/",
      "proofs/",
      "runs/",
      "refs/",
      "build/",
      ".rk/",
      ".frontier/",
      ".beads/",
      "docs/worklog.md",
      "CLAUDE.md",
      "AGENTS.md",
      "PRD.md",
      "HANDOFF.md",
      "CONVENTIONS.md",
      "FINDINGS.md",
    ]) {
      expect(paths).toContain(required);
    }
  });

  test("CLAUDE.md and AGENTS.md stamp from the same template (byte-identical constitution)", () => {
    const claude = manifest.stamped.find((e: { path: string }) => e.path === "CLAUDE.md");
    const agents = manifest.stamped.find((e: { path: string }) => e.path === "AGENTS.md");
    expect(claude.template).toBe(agents.template);
    expect(claude.template).toBe("CLAUDE.md.tmpl");
  });

  // rk-o1y: the M1.4 upgrade stub exists to notice exactly this kind of template-content change
  // — a stamped repo carrying an older template_version must MISMATCH a binary carrying this one.
  test("template_version was bumped to 1.1.0 for the shard-schema template addition (rk-o1y)", () => {
    expect(manifest.template_version).toBe("1.1.0");
  });

  test("definitions/README.md and argument/README.md are stamped, rewritten-whole (rk-o1y)", () => {
    for (const [path, template] of [
      ["definitions/README.md", "definitions/README.md.tmpl"],
      ["argument/README.md", "argument/README.md.tmpl"],
    ]) {
      const entry = manifest.stamped.find((e: { path: string }) => e.path === path);
      expect(entry).toBeDefined();
      expect(entry.template).toBe(template);
      expect(entry.classification).toBe("rewritten-whole");
    }
  });
});

// rk-o1y: the stamped schema docs must be derived from docs/gate-contracts.md Gates 1-2 — field
// names and allowed enums cited precisely — with one complete minimal example shard each, so a
// newcomer can author a first shard without reverse-engineering the gates via iterative WARNs.
describe("templates / (e) shard schema docs (rk-o1y)", () => {
  const defsReadme = read("definitions/README.md.tmpl");
  const argReadme = read("argument/README.md.tmpl");

  test("definitions/README.md.tmpl cites every Gate 1 frontmatter field and enum value", () => {
    for (const token of [
      "id", "term", "aliases", "kind", "status", "source", "locus", "sha256", "consensus",
      "cited", "consensus", "original", // kind enum
      "draft", "locked", // status enum
    ]) {
      expect(defsReadme).toContain(token);
    }
    // one complete, fenced, generic example shard — not real campaign content
    expect(defsReadme).toContain("def-widget");
    expect(defsReadme).toMatch(/```markdown\n---\nid: def-widget/);
  });

  test("argument/README.md.tmpl cites every Gate 2 frontmatter field and enum value", () => {
    for (const token of [
      "id", "kind", "contract", "defs", "deps", "routes", "status", "af", "provenance", "owner", "workspace",
      "lemma", "proposition", "theorem", "corollary", "open-problem", "obstruction", // kind enum
      "none", "seeded", "validated", // af enum
    ]) {
      expect(argReadme).toContain(token);
    }
    expect(argReadme).toContain("lem-widget-bound");
    expect(argReadme).toMatch(/```markdown\n---\nid: lem-widget-bound/);
  });

  test("neither schema doc carries campaign-flavored content (generic widget example only)", () => {
    for (const forbidden of ["idempotent", "stochastic", "conjecture C", "af-orchestrate"]) {
      expect(defsReadme.toLowerCase()).not.toContain(forbidden.toLowerCase());
      expect(argReadme.toLowerCase()).not.toContain(forbidden.toLowerCase());
    }
  });
});
